USE IVA

CREATE TABLE TB_CADASTRAR_MEMBRO(
	IDMEMBRO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	SENHA VARCHAR(30) NOT NULL
);

CREATE TABLE TB_LOGIN_MEMBRO(
	IDLOGIN INT PRIMARY KEY AUTO_INCREMENT, 
	EMAIL VARCHAR(30) NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	ID_MEMBRO INT UNIQUE,

	FOREIGN KEY(ID_MEMBRO)
	REFERENCES TB.CADASTRAR_MEMBRO(IDMEMBRO)
);